# Basic
title: éƒ­é”…
subtitle: Fighting  
description: Welcome come to my blog~
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: éƒ­é”…   
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: åƒæ¯é†‰ä¸å€’ï¼Œå”¯æˆ‘é…’å‰‘ä»™
url: "https://jp3drobin.github.io/"

 #Comment
 #comment:
 #   provider: duoshuo
 #   duoshuo:
  #  short_name: 

# Social
social:
    weibo: 89386058@qq.com
    weixing: aminp1    
    github: jp3drobin
    twitter: Roban666
    mail: hnlyprogrammer@gmail.com
 #   csdn:

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
  id: c7ece662e8dda9edc637a34031b68641
      

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
#ga:
# id: UA-84134159-3   
#  host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/jp3dRobin/jp3dRobin.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}   
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}   
    - {title: å­¦ä¹ èµ„æ–™, description: ziliao, url: '/ziliao'}
    - {title: å…³äºæˆ‘, description: about, url: '/about'}

          
    

# Pagination
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"


